### ISSUE TITLE
Binding fails if total XML document length is greater than 1800 characters

### ISSUE THREAD

**Issue by ZacharyKlein** [micronaut-projects/micronaut-jackson-xml#130]
### Expected Behavior

When binding XML from a POST endpoint, the entire document should be parsed, regardless of length.

### Actual Behaviour

An error is thrown if the XML document is 1801 characters or more in total length: 

```
17:36:39.304 [default-nioEventLoopGroup-1-24] ERROR i.m.x.j.s.c.XmlStreamConvertibleValues - Failed to read the xml stream as a tree
com.fasterxml.jackson.core.JsonParseException: Unexpected end of input block in end tag
 at [row,col {unknown-source}]: [4,5]
 at [Source: (byte[])"<xml>

<content>dadasdadadaddassdsaddadasdadadaddassdsaddadasdadadaddassdsaddadasdadadaddassdsaddadasdadadaddassdsaddadasdadadaddassdsaddadasdadadaddassdsaddadasdadadaddassdsaddadasdadadaddassdsaddadasdadadaddassdsaddadasdadadaddassdsaddadasdadadaddassdsaddadasdadadaddassdsaddadasdadadaddassddassaddadasdadadaddassdsaddadasdadadaddassdsaddadasdadadaddassdsaddadasdadadaddassdsaddadasdadadaddassdsaddadasdadadaddassdsaddadasdadadaddassdsaddafsaddasdadadaddassdsaddadasdadadaddassdsaddadasdadadaddassd"[truncated 1367 bytes]; line: 4, column: 6]
	at com.fasterxml.jackson.dataformat.xml.util.StaxUtil.throwAsParseException(StaxUtil.java:41)
	at com.fasterxml.jackson.dataformat.xml.deser.FromXmlParser._nextToken(FromXmlParser.java:1363)
	at com.fasterxml.jackson.dataformat.xml.deser.FromXmlParser.nextToken(FromXmlParser.java:681)
	at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:986)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:269)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:16)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:91)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4635)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3056)
	at io.micronaut.xml.jackson.server.convert.XmlStreamConvertibleValues.lambda$new$0(XmlStreamConvertibleValues.java:66)
	at io.micronaut.core.util.SupplierUtil$1.initialize(SupplierUtil.java:48)
	at io.micronaut.core.util.SupplierUtil$1.get(SupplierUtil.java:43)
	at io.micronaut.xml.jackson.server.convert.XmlStreamConvertibleValues.get(XmlStreamConvertibleValues.java:144)
	at io.micronaut.core.bind.annotation.AbstractAnnotatedArgumentBinder.resolveValue(AbstractAnnotatedArgumentBinder.java:127)
	at io.micronaut.core.bind.annotation.AbstractAnnotatedArgumentBinder.doResolve(AbstractAnnotatedArgumentBinder.java:102)
	at io.micronaut.core.bind.annotation.AbstractAnnotatedArgumentBinder.doBind(AbstractAnnotatedArgumentBinder.java:85)
	at io.micronaut.core.bind.annotation.AbstractAnnotatedArgumentBinder.doBind(AbstractAnnotatedArgumentBinder.java:66)
	at io.micronaut.http.bind.binders.ParameterAnnotationBinder.bind(ParameterAnnotationBinder.java:87)
	at io.micronaut.http.bind.binders.ParameterAnnotationBinder.bind(ParameterAnnotationBinder.java:39)
	at io.micronaut.http.server.binding.RequestArgumentSatisfier.lambda$getValueForArgument$3(RequestArgumentSatisfier.java:146)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:265)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:121)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.emitRouteResponse(RoutingInBoundHandler.java:1502)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.access$2100(RoutingInBoundHandler.java:151)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$6$1.request(RoutingInBoundHandler.java:1469)
	at io.reactivex.internal.subscriptions.SubscriptionHelper.deferredSetOnce(SubscriptionHelper.java:202)
	at io.reactivex.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.onSubscribe(SingleFlatMapPublisher.java:107)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$6.doSubscribe(RoutingInBoundHandler.java:1457)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$6.subscribe(RoutingInBoundHandler.java:1448)
	at io.reactivex.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.onSuccess(SingleFlatMapPublisher.java:102)
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:67)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$4.doOnComplete(RoutingInBoundHandler.java:1069)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onComplete(CompletionAwareSubscriber.java:71)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.micronaut.core.async.processor.SingleThreadedBufferingProcessor.doOnComplete(SingleThreadedBufferingProcessor.java:48)
	at io.micronaut.xml.jackson.server.XmlContentProcessor.doOnComplete(XmlContentProcessor.java:83)
	at io.micronaut.core.async.subscriber.SingleThreadedBufferingSubscriber.onComplete(SingleThreadedBufferingSubscriber.java:70)
	at io.micronaut.http.netty.reactive.HandlerPublisher.complete(HandlerPublisher.java:416)
	at io.micronaut.http.netty.reactive.HandlerPublisher.handlerRemoved(HandlerPublisher.java:403)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:946)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:637)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:477)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.removeHandlerIfActive(HttpStreamsHandler.java:441)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:295)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:258)
	at io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:123)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:200)
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:162)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: com.ctc.wstx.exc.WstxEOFException: Unexpected end of input block in end tag
 at [row,col {unknown-source}]: [4,5]
	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedEOB(StreamScanner.java:714)
	at com.ctc.wstx.sr.StreamScanner.loadMoreFromCurrent(StreamScanner.java:1081)
	at com.ctc.wstx.sr.StreamScanner.getNextCharFromCurrent(StreamScanner.java:819)
	at com.ctc.wstx.sr.BasicStreamReader.readEndElem(BasicStreamReader.java:3310)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2918)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1122)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlTokenStream._skipAndCollectTextUntilTag(XmlTokenStream.java:588)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlTokenStream._next(XmlTokenStream.java:490)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlTokenStream.next(XmlTokenStream.java:275)
	at com.fasterxml.jackson.dataformat.xml.deser.FromXmlParser._nextToken(FromXmlParser.java:1361)
	... 92 common frames omitted

```

### Steps To Reproduce

1. Checkout the demo in the linked repo
2. Startup with `./gradlew run`
3. Execute the CURL command provided in the README to see trigger the error
4. Remove one character from the `<content>` value to get a successful response.

### Environment Information

- Operation System: macOS
- JDK 16

### Example Application

https://github.com/ZacharyKlein/micronaut-xml-length-issue

### Version

3.0.0-M5 (and 2.5.11)

**Comment by ZacharyKlein** [comment]
Here are some configuration properties for Woodstox, which might be relevant (I don't know how to set these in Micronaut): http://fasterxml.github.io/woodstox/javadoc/5.0/com/ctc/wstx/api/WstxInputProperties.html#P_MAX_CHARACTERS
