### ISSUE TITLE
Error on starting Micronaut Server

### ISSUE THREAD

**Issue by JEDIBC** [micronaut-projects/micronaut-jackson-xml#2]
Hi,

I've just added the maven dependency in my micronaut app and I obtain the following startup error :

```
17:47:46.899 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error loading bean [io.micronaut.xml.jackson.server.convert.XmlStreamToObjectConverter]: io/micronaut/inject/annotation/AnnotationMetadataHierarchy
io.micronaut.context.exceptions.BeanContextException: Error loading bean [io.micronaut.xml.jackson.server.convert.XmlStreamToObjectConverter]: io/micronaut/inject/annotation/AnnotationMetadataHierarchy
	at io.micronaut.context.DefaultBeanContext.lambda$findBeanCandidates$32(DefaultBeanContext.java:1419)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:1429)
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:241)
	at io.micronaut.context.DefaultBeanContext.lambda$findBeanCandidatesInternal$68(DefaultBeanContext.java:2473)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.lambda$compute$0(ConcurrentLinkedHashMap.java:721)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.compute(ConcurrentLinkedHashMap.java:733)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.computeIfAbsent(ConcurrentLinkedHashMap.java:710)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidatesInternal(DefaultBeanContext.java:2473)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2511)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:894)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:620)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:350)
	at io.micronaut.context.DefaultApplicationContext.initializeTypeConverters(DefaultApplicationContext.java:414)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:235)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2446)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:200)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:187)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:307)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:293)
	at my.Application.main(Application.java:17)
Caused by: java.lang.NoClassDefFoundError: io/micronaut/inject/annotation/AnnotationMetadataHierarchy
	at io.micronaut.xml.jackson.server.convert.$XmlStreamToObjectConverterDefinition.<init>(Unknown Source)
	at io.micronaut.xml.jackson.server.convert.$XmlStreamToObjectConverterDefinitionClass.load(Unknown Source)
	at io.micronaut.context.AbstractBeanDefinitionReference.load(AbstractBeanDefinitionReference.java:63)
	at io.micronaut.context.DefaultBeanContext.lambda$findBeanCandidates$32(DefaultBeanContext.java:1417)
	... 29 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.micronaut.inject.annotation.AnnotationMetadataHierarchy
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 33 common frames omitted
```

Is there some configuration or dependency that I'm missing ?

Thanks

regards,

Bruno

**Comment by graemerocher** [comment]
As per the README you need Micronaut 1.3+

**Comment by JEDIBC** [comment]
My bad, I thought I was on the 1.3.0-SNAPSHOT but was still on 1.2.10

**Comment by graemerocher** [comment]
1.3.0 has been released so you don’t need the snapshot anymore

**Comment by JEDIBC** [comment]
Yeah I've updated my project and it works fine.

However, content negociation doesn't seem to be automatic. I had `@Consumes({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})` and `@Produces({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})` on my controllers but when I request with `accept: application/xml` it still return json data.

Thanks

**Comment by graemerocher** [comment]
Could you report an issue to https://github.com/micronaut-projects/micronaut-core/issues with an example. Thanks.

**Comment by JEDIBC** [comment]
Done https://github.com/micronaut-projects/micronaut-core/issues/2743
